image: maven:3.5-jdk-10

stages:
  - test
  - deploy


  - cd project
java:
  stage: test
  script: "mvn package"
  artifacts:
    reports:
      junit:
        - project/test/results/test.xml
      
      
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r project/javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
