image: java:latest

stages:
  - test
  - deploy

java:
  stage: test
  script:
    - gradle test
      
      
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r project/javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
