image: maven:3.5-jdk-10

stages:
  - test
  - deploy


maven_build:
  stage: test
  script:
    - echo "building my amazing repo..."
    - mvn test
    - 'curl -H "Content-Type: multipart/form-data" -u $jira_user:$jira_password -F "file=@target/surefire-reports/TEST-com.xpand.java.CalcTest.xml" "$jira_server_url/rest/raven/1.0/import/execution/junit?projectKey=CALC"'
    - echo "done"
      
      
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r project/javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
