image: maven:alpine

stages:
  - test
  - deploy
  
test:
  stage: test
  script: 
    - cd project
    - mvn test
      
      
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r project/javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

