image: maven:alpine

stages:
  - test
  - deploy


java:
  stage: test
  script:
    - cd project
    - mvn verify
  artifacts:
    reports:
      junit:
        - project/target/surefire-reports/TEST*.xml
      
      
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r project/javadoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
